spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: tsYjqfXvytINvKw8g8wN
            client-secret: epkbwsgLAL
            client-name: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 1022efadfecf47403c347b18bddf0b5a
            client-secret: PBCGDJKT0yCIDWKZ2RFojifdXyRoNv5H
            client-name: Kakao
            client-authentication-method: POST
            redirect-uri: http://localhost:9999/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - name
              - birthday
              - phone_number
 
 
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id